### ISSUE TITLE
Cattalog causes partys to mess up.

### ISSUE THREAD

**Issue by daviddave** [ToontownInfinite/src#325]
Hi. Pretty much says everything above. But it Messes up time manager after it messed up toonbase!

**Comment by daviddave** [comment]
here is the log

ToontownStart: Polling for game2 to finish...
ToontownStart: Game2 is finished.
ToontownStart: Starting the game.
ToontownStart: setting default font
TTLocalizer: Running in language: english
from toontown.toonbase.TTLocalizerEnglish import *
OTPLocalizer: Running in language: english
from otp.otpbase.OTPLocalizerEnglish import *
ToontownStart: Loading default gui sounds
ToontownStart: serverVersion:  ttr-1.0.0
Preloading avatars...
Done preloading avatars.
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Users\david\Downloads\toontown reborn\ttr\toontown\toonbase\ToontownStart.py", line 130, in <module>
    cr = ToontownClientRepository.ToontownClientRepository(serverVersion, launcher)
  File "toontown\distributed\ToontownClientRepository.py", line 95, in __init__
    self.toontownTimeManager = ToontownTimeManager.ToontownTimeManager()
  File "toontown\parties\ToontownTimeManager.py", line 16, in __init__
    self.serverTimeZone = ToontownTimeZone()
  File "toontown\parties\ToontownTimeZone.py", line 33, in __init__
    self.stdName, self.dstName, self.stdOffset = timeZoneInfo.split('/')
ValueError: need more than 2 values to unpack
