### ISSUE TITLE
Building gamedat.pyd eror relly need help!!!!!!

### ISSUE THREAD

**Issue by Midnighters** [ToontownInfinite/src#345]
C:\Users\Administrator\Desktop\src-master>C:\Panda3D-1.9.0\python\python.exe -m
build_client.py
Building the client...
couldn't import shared
couldn't import infinite
couldn't import direct.extensions
couldn't import direct.extensions
Traceback (most recent call last):
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "C:\Panda3D-1.9.0\python\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Panda3D-1.9.0\direct\showutil\pfreeze.py", line 117, in <module>
    freezer.done(compileToExe = compileToExe)
  File "C:\Panda3D-1.9.0\direct\showutil\FreezeTool.py", line 886, in done
    self.__loadModule(mdef)
  File "C:\Panda3D-1.9.0\direct\showutil\FreezeTool.py", line 974, in __loadModu
le
    fp = open(pathname, modulefinder.READ_MODE)
IOError: [Errno 2] No such file or directory: 'toontown.toonbase.ClientStart'
Done building the client.
C:\Panda3D-1.9.0\python\python.exe: No module named build_client.py

C:\Users\Administrator\Desktop\src-master>pause
Press any key to continue . . .

**Comment by judge2020** [comment]
you got an error

**Comment by brownzilla** [comment]
Make your own compiler.

**Comment by mgracer48** [comment]
lol good one

**Comment by brownzilla** [comment]
I did, not hard.
